/* SPDX-License-Identifier: Apache-2.0
 * Copyright (C) 2026 Sean Pollard <spollard08@gmail.com>
 *
 * camera/NdkCameraMetadataTags.h — Camera2 metadata tag identifiers and the
 * enum value constants for the tags this shim's consumers read/write.
 *
 * Every tag is (section << 16) + index, so the section-start enum makes each
 * tag self-evidently correct against AOSP.  Only the subset currently used is
 * declared; extend as needed — adding a tag here is purely additive.  Values
 * match the public Android NDK ABI exactly (a wrong value is a latent runtime
 * bug, not a compile error).
 */

#ifndef CAMERA2NDK_HYBRIS_CAMERA_NDKCAMERAMETADATATAGS_H
#define CAMERA2NDK_HYBRIS_CAMERA_NDKCAMERAMETADATATAGS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum acamera_metadata_section_start {
    ACAMERA_COLOR_CORRECTION_START = 0u << 16,
    ACAMERA_CONTROL_START     = 1u  << 16,
    ACAMERA_EDGE_START        = 3u  << 16,
    ACAMERA_FLASH_START       = 4u  << 16,
    ACAMERA_NOISE_REDUCTION_START = 10u << 16,
    ACAMERA_JPEG_START        = 7u  << 16,
    ACAMERA_LENS_START        = 8u  << 16,
    ACAMERA_LENS_INFO_START   = 9u  << 16,
    ACAMERA_REQUEST_START     = 12u << 16,
    ACAMERA_SCALER_START      = 13u << 16,
    ACAMERA_SENSOR_START      = 14u << 16,
    ACAMERA_SENSOR_INFO_START = 15u << 16,
    ACAMERA_INFO_START        = 21u << 16,
} acamera_metadata_section_start;

typedef enum acamera_metadata_tag {
    /* COLOR_CORRECTION — per-frame WB gains (result side), for DNG AsShotNeutral. */
    ACAMERA_COLOR_CORRECTION_GAINS                 = ACAMERA_COLOR_CORRECTION_START + 2,

    /* CONTROL — request-side controls + the FPS-range list. */
    ACAMERA_CONTROL_AE_EXPOSURE_COMPENSATION       = ACAMERA_CONTROL_START + 1,
    ACAMERA_CONTROL_AE_LOCK                        = ACAMERA_CONTROL_START + 2,
    ACAMERA_CONTROL_AE_MODE                        = ACAMERA_CONTROL_START + 3,
    ACAMERA_CONTROL_AE_REGIONS                     = ACAMERA_CONTROL_START + 4,
    ACAMERA_CONTROL_AE_TARGET_FPS_RANGE            = ACAMERA_CONTROL_START + 5,
    ACAMERA_CONTROL_AE_PRECAPTURE_TRIGGER          = ACAMERA_CONTROL_START + 6,
    ACAMERA_CONTROL_AF_MODE                        = ACAMERA_CONTROL_START + 7,
    ACAMERA_CONTROL_AF_REGIONS                     = ACAMERA_CONTROL_START + 8,
    ACAMERA_CONTROL_AF_TRIGGER                     = ACAMERA_CONTROL_START + 9,
    ACAMERA_CONTROL_AWB_LOCK                       = ACAMERA_CONTROL_START + 10,
    ACAMERA_CONTROL_AWB_MODE                       = ACAMERA_CONTROL_START + 11,
    ACAMERA_CONTROL_MODE                           = ACAMERA_CONTROL_START + 15,
    ACAMERA_CONTROL_SCENE_MODE                     = ACAMERA_CONTROL_START + 16,
    ACAMERA_CONTROL_VIDEO_STABILIZATION_MODE       = ACAMERA_CONTROL_START + 17,
    ACAMERA_CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES = ACAMERA_CONTROL_START + 20,
    ACAMERA_CONTROL_AE_COMPENSATION_RANGE          = ACAMERA_CONTROL_START + 21,
    ACAMERA_CONTROL_AE_COMPENSATION_STEP           = ACAMERA_CONTROL_START + 22,
    ACAMERA_CONTROL_AVAILABLE_SCENE_MODES          = ACAMERA_CONTROL_START + 25,
    ACAMERA_CONTROL_AVAILABLE_VIDEO_STABILIZATION_MODES = ACAMERA_CONTROL_START + 26,
    ACAMERA_CONTROL_AE_STATE                       = ACAMERA_CONTROL_START + 31,
    ACAMERA_CONTROL_ZOOM_RATIO_RANGE               = ACAMERA_CONTROL_START + 46,
    ACAMERA_CONTROL_ZOOM_RATIO                     = ACAMERA_CONTROL_START + 47,

    /* EDGE — edge enhancement (sharpening) mode + its availability list. */
    ACAMERA_EDGE_MODE                              = ACAMERA_EDGE_START + 0,
    ACAMERA_EDGE_AVAILABLE_EDGE_MODES              = ACAMERA_EDGE_START + 2,

    ACAMERA_FLASH_MODE                             = ACAMERA_FLASH_START + 2,

    /* NOISE_REDUCTION — denoise mode + its availability list. */
    ACAMERA_NOISE_REDUCTION_MODE                   = ACAMERA_NOISE_REDUCTION_START + 0,
    ACAMERA_NOISE_REDUCTION_AVAILABLE_NOISE_REDUCTION_MODES = ACAMERA_NOISE_REDUCTION_START + 2,

    ACAMERA_JPEG_ORIENTATION                       = ACAMERA_JPEG_START + 3,
    ACAMERA_JPEG_QUALITY                           = ACAMERA_JPEG_START + 4,

    ACAMERA_LENS_FACING                            = ACAMERA_LENS_START + 5,
    ACAMERA_LENS_INFO_AVAILABLE_FOCAL_LENGTHS      = ACAMERA_LENS_INFO_START + 2,

    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES         = ACAMERA_REQUEST_START + 12,

    ACAMERA_SCALER_AVAILABLE_STREAM_CONFIGURATIONS = ACAMERA_SCALER_START + 10,

    /* SENSOR — request-side manual controls and characteristics we log. */
    ACAMERA_SENSOR_EXPOSURE_TIME                   = ACAMERA_SENSOR_START + 0,
    ACAMERA_SENSOR_FRAME_DURATION                  = ACAMERA_SENSOR_START + 1,
    ACAMERA_SENSOR_SENSITIVITY                     = ACAMERA_SENSOR_START + 2,
    /* DNG color characteristics (static): rational[9] matrices + byte illuminants. */
    ACAMERA_SENSOR_REFERENCE_ILLUMINANT1           = ACAMERA_SENSOR_START + 3,
    ACAMERA_SENSOR_REFERENCE_ILLUMINANT2           = ACAMERA_SENSOR_START + 4,
    ACAMERA_SENSOR_CALIBRATION_TRANSFORM1          = ACAMERA_SENSOR_START + 5,
    ACAMERA_SENSOR_CALIBRATION_TRANSFORM2          = ACAMERA_SENSOR_START + 6,
    ACAMERA_SENSOR_COLOR_TRANSFORM1                = ACAMERA_SENSOR_START + 7,
    ACAMERA_SENSOR_COLOR_TRANSFORM2                = ACAMERA_SENSOR_START + 8,
    ACAMERA_SENSOR_FORWARD_MATRIX1                 = ACAMERA_SENSOR_START + 9,
    ACAMERA_SENSOR_FORWARD_MATRIX2                 = ACAMERA_SENSOR_START + 10,
    ACAMERA_SENSOR_BLACK_LEVEL_PATTERN             = ACAMERA_SENSOR_START + 12,
    ACAMERA_SENSOR_ORIENTATION                     = ACAMERA_SENSOR_START + 14,
    ACAMERA_SENSOR_NEUTRAL_COLOR_POINT             = ACAMERA_SENSOR_START + 18,

    ACAMERA_SENSOR_INFO_ACTIVE_ARRAY_SIZE          = ACAMERA_SENSOR_INFO_START + 0,
    ACAMERA_SENSOR_INFO_SENSITIVITY_RANGE          = ACAMERA_SENSOR_INFO_START + 1,
    ACAMERA_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT   = ACAMERA_SENSOR_INFO_START + 2,
    ACAMERA_SENSOR_INFO_EXPOSURE_TIME_RANGE        = ACAMERA_SENSOR_INFO_START + 3,
    ACAMERA_SENSOR_INFO_PHYSICAL_SIZE              = ACAMERA_SENSOR_INFO_START + 5,
    ACAMERA_SENSOR_INFO_PIXEL_ARRAY_SIZE           = ACAMERA_SENSOR_INFO_START + 6,
    ACAMERA_SENSOR_INFO_WHITE_LEVEL                = ACAMERA_SENSOR_INFO_START + 7,
    ACAMERA_SENSOR_INFO_PRE_CORRECTION_ACTIVE_ARRAY_SIZE = ACAMERA_SENSOR_INFO_START + 10,

    ACAMERA_INFO_SUPPORTED_HARDWARE_LEVEL          = ACAMERA_INFO_START + 0,
} acamera_metadata_tag;

/* ── Enum value constants for the tags above ─────────────────────────────── */

enum {
    ACAMERA_LENS_FACING_FRONT    = 0,
    ACAMERA_LENS_FACING_BACK     = 1,
    ACAMERA_LENS_FACING_EXTERNAL = 2,
};
enum {
    ACAMERA_INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED  = 0,
    ACAMERA_INFO_SUPPORTED_HARDWARE_LEVEL_FULL     = 1,
    ACAMERA_INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY   = 2,
    ACAMERA_INFO_SUPPORTED_HARDWARE_LEVEL_3        = 3,
    ACAMERA_INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL = 4,
};
enum {
    ACAMERA_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_OUTPUT = 0,
    ACAMERA_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_INPUT  = 1,
};
enum {
    ACAMERA_EDGE_MODE_OFF              = 0,
    ACAMERA_EDGE_MODE_FAST            = 1,
    ACAMERA_EDGE_MODE_HIGH_QUALITY    = 2,
    ACAMERA_EDGE_MODE_ZERO_SHUTTER_LAG = 3,
};
enum {
    ACAMERA_NOISE_REDUCTION_MODE_OFF           = 0,
    ACAMERA_NOISE_REDUCTION_MODE_FAST          = 1,
    ACAMERA_NOISE_REDUCTION_MODE_HIGH_QUALITY  = 2,
    ACAMERA_NOISE_REDUCTION_MODE_MINIMAL       = 3,
    ACAMERA_NOISE_REDUCTION_MODE_ZERO_SHUTTER_LAG = 4,
};
enum {
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_BACKWARD_COMPATIBLE    = 0,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_MANUAL_SENSOR          = 1,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_MANUAL_POST_PROCESSING = 2,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_RAW                    = 3,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_READ_SENSOR_SETTINGS   = 5,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_BURST_CAPTURE          = 6,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_DEPTH_OUTPUT           = 8,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_MOTION_TRACKING        = 10,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_LOGICAL_MULTI_CAMERA   = 11,
    ACAMERA_REQUEST_AVAILABLE_CAPABILITIES_MONOCHROME             = 12,
};
enum {
    ACAMERA_CONTROL_AE_MODE_OFF             = 0,
    ACAMERA_CONTROL_AE_MODE_ON              = 1,
    ACAMERA_CONTROL_AE_MODE_ON_AUTO_FLASH   = 2,
    ACAMERA_CONTROL_AE_MODE_ON_ALWAYS_FLASH = 3,
};
enum { ACAMERA_CONTROL_AE_LOCK_OFF  = 0, ACAMERA_CONTROL_AE_LOCK_ON  = 1 };
enum { ACAMERA_CONTROL_AWB_LOCK_OFF = 0, ACAMERA_CONTROL_AWB_LOCK_ON = 1 };
enum {
    ACAMERA_CONTROL_AWB_MODE_OFF              = 0,
    ACAMERA_CONTROL_AWB_MODE_AUTO             = 1,
    ACAMERA_CONTROL_AWB_MODE_INCANDESCENT     = 2,
    ACAMERA_CONTROL_AWB_MODE_FLUORESCENT      = 3,
    ACAMERA_CONTROL_AWB_MODE_WARM_FLUORESCENT = 4,
    ACAMERA_CONTROL_AWB_MODE_DAYLIGHT         = 5,
    ACAMERA_CONTROL_AWB_MODE_CLOUDY_DAYLIGHT  = 6,
    ACAMERA_CONTROL_AWB_MODE_TWILIGHT         = 7,
    ACAMERA_CONTROL_AWB_MODE_SHADE            = 8,
};
enum {
    ACAMERA_CONTROL_AF_MODE_OFF                = 0,
    ACAMERA_CONTROL_AF_MODE_AUTO               = 1,
    ACAMERA_CONTROL_AF_MODE_MACRO              = 2,
    ACAMERA_CONTROL_AF_MODE_CONTINUOUS_VIDEO   = 3,
    ACAMERA_CONTROL_AF_MODE_CONTINUOUS_PICTURE = 4,
    ACAMERA_CONTROL_AF_MODE_EDOF               = 5,
};
enum {
    ACAMERA_CONTROL_AF_TRIGGER_IDLE   = 0,
    ACAMERA_CONTROL_AF_TRIGGER_START  = 1,
    ACAMERA_CONTROL_AF_TRIGGER_CANCEL = 2,
};
enum { ACAMERA_FLASH_MODE_OFF = 0, ACAMERA_FLASH_MODE_SINGLE = 1, ACAMERA_FLASH_MODE_TORCH = 2 };
enum {
    ACAMERA_CONTROL_VIDEO_STABILIZATION_MODE_OFF = 0,
    ACAMERA_CONTROL_VIDEO_STABILIZATION_MODE_ON  = 1,
};
enum {
    ACAMERA_CONTROL_MODE_OFF            = 0,
    ACAMERA_CONTROL_MODE_AUTO           = 1,
    ACAMERA_CONTROL_MODE_USE_SCENE_MODE = 2,
    ACAMERA_CONTROL_MODE_OFF_KEEP_STATE = 3,
};
enum {
    ACAMERA_CONTROL_SCENE_MODE_DISABLED = 0,
    ACAMERA_CONTROL_SCENE_MODE_ACTION   = 2,   // freeze motion: short shutter, higher ISO
    ACAMERA_CONTROL_SCENE_MODE_SPORTS   = 13,
};

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* CAMERA2NDK_HYBRIS_CAMERA_NDKCAMERAMETADATATAGS_H */
